#!/bin/bash

#default IP address of Omega
ipAddr="192.168.3.1"

#check for a config file that defines another IP Address
file="config.ini"
param="ipAddr"

cd `dirname $0`
if [ -f "$file" ]; then
	ipAddr=`cat $file | grep -v "^#" | grep -v "^$" | grep "^$param" | sed -e 's/.*=//'`
fi
cd -
echo "Omega IP: $ipAddr"


# transfer files
rm -rf dist
mkdir dist
cp -r elements apps fonts helpers images index.html lib services views dist

find dist -name "*bower*" -exec rm -rf {} \; 2>&1
find dist -name "demo" -exec rm -rf {} \; 2>&1
find dist -name "test" -exec rm -rf {} \; 2>&1
find dist -name "*.md" -exec rm -rf {} \; 2>&1
find dist -name "LICENSE*" -exec rm -rf {} \; 2>&1
find dist -name "COPYING*" -exec rm -rf {} \; 2>&1
find dist -name "package.json" -exec rm -rf {} \; 2>&1
find dist -name ".git*" -exec rm -rf {} \; 2>&1
find dist -name ".DS_Store" -exec rm -rf {} \; 2>&1

rsync --progress -rv ./dist/* root@$ipAddr:/www

rm -rf dist
